import React, { ReactNode, useState, useEffect } from 'react';
import { NavLink, useLocation } from 'react-router-dom';
import { NAV_ITEMS, THEMES } from '../constants';
import { ThemeType } from '../types';
import { Bell, Palette, Moon, Sun, Monitor, X, ChevronRight, LogOut, User, Lock, Copy, Check } from 'lucide-react';
import { supabase } from '../supabase';

interface LayoutProps {
  children: ReactNode;
  currentTheme: ThemeType;
  setTheme: (theme: ThemeType) => void;
  user?: any;
}

const Layout: React.FC<LayoutProps> = ({ children, currentTheme, setTheme, user }) => {
  const location = useLocation();
  const [showAppearance, setShowAppearance] = useState(false);
  const [showAdminModal, setShowAdminModal] = useState(false);
  const [adminPassword, setAdminPassword] = useState('');
  const [isAdminAuthenticated, setIsAdminAuthenticated] = useState(false);
  const [copied, setCopied] = useState(false);
  
  // Initialize dark mode from localStorage, default to false (Light Mode)
  const [isDarkMode, setIsDarkMode] = useState(() => {
    const saved = localStorage.getItem('ttsp_dark_mode');
    return saved !== null ? JSON.parse(saved) : false;
  });

  // Apply dark mode class and save to localStorage
  useEffect(() => {
    if (isDarkMode) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
    localStorage.setItem('ttsp_dark_mode', JSON.stringify(isDarkMode));
  }, [isDarkMode]);

  const handleLogout = async () => {
    await supabase.auth.signOut();
  };

  const handleAdminAuth = () => {
    if (adminPassword === 'DAN2026') {
        setIsAdminAuthenticated(true);
    } else {
        alert('Invalid Access Code');
    }
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const getThemeClass = (theme: ThemeType) => {
    return THEMES.find((t) => t.value === theme)?.class || THEMES[0].class;
  };

  // Get initials for avatar
  const getInitials = () => {
    if (!user?.user_metadata?.full_name) return 'Guest';
    const names = user.user_metadata.full_name.split(' ');
    if (names.length >= 2) return `${names[0][0]}${names[1][0]}`.toUpperCase();
    return names[0][0].toUpperCase();
  };

  const SQL_SCHEMA = `
-- ==========================================
-- 1. Create the PDR Records Table
-- ==========================================
create table if not exists public.pdr_records (
  id bigint generated by default as identity primary key,
  department text,
  group_name text,
  team text,
  year integer,
  billing_month text,
  ship_number text,
  revision_series_number text,
  revision_number text,
  industry_number text,
  block_name_or_drawing_name text,
  drawing_number text,
  issuance_date text,
  original_t_dreams_delivery text,
  manhour_spent numeric,
  responsible_team text,
  origin text,
  designer text,
  checker text,
  revised_by text,
  reason_of_revision text,
  design_update_code text,
  from_d_number text,
  type_of_error text,
  detail_cause_of_error text,
  general_cause_of_error text,
  damage text,
  number_of_piece_with_damage integer,
  number_of_piece_without_damage integer,
  cost_of_damage numeric,
  remarks text,
  revision_family_number text,
  add_info text,
  update_info text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.pdr_records enable row level security;

-- Allow all operations for development
create policy "Allow all operations for everyone"
on public.pdr_records for all using (true) with check (true);

-- ==========================================
-- 2. AUTOMATIC USER PROFILE CREATION
-- (Works with Outlook/Azure AD Login)
-- ==========================================

-- A. Create the 'profiles' table to store user data
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text,
  full_name text,
  department text,
  role text default 'user',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- B. Enable Security
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone"
  on profiles for select
  using ( true );

create policy "Users can update own profile"
  on profiles for update
  using ( auth.uid() = id );

-- C. Create the Trigger Function
-- This function runs automatically whenever a new user logs in via Outlook
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, department)
  values (
    new.id,
    new.email,
    -- Extracts 'full_name' from the Outlook/Azure metadata
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    'Unassigned'
  );
  return new;
end;
$$;

-- D. Attach Trigger to Auth System
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
  `;

  return (
    <div className={`min-h-screen w-full transition-all duration-500 ${getThemeClass(currentTheme)} ${isDarkMode ? 'dark' : ''} flex overflow-hidden`}>
      
      {/* Desktop Sidebar */}
      <aside className="hidden md:flex flex-col w-64 glass-panel border-r-0 border-r-white/5 h-screen sticky top-0 z-50 shadow-xl">
        <div className="p-6 flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-blue-600 to-indigo-600 flex items-center justify-center font-bold text-white shadow-lg shadow-blue-500/30">
            T
          </div>
          <span className="font-bold text-lg tracking-wide text-slate-900 dark:text-white">TTSP Manager</span>
        </div>
        
        <div className="flex-1 overflow-y-auto py-4 px-3 space-y-1 custom-scrollbar">
          {NAV_ITEMS.map((item) => {
            const isActive = location.pathname === item.path;
            return (
              <NavLink
                key={item.name}
                to={item.path}
                className={`flex items-center gap-3 px-4 py-3 rounded-xl transition-all duration-200 group relative overflow-hidden ${
                  isActive 
                    ? 'bg-blue-50 dark:bg-blue-600/10 shadow-sm text-blue-700 dark:text-blue-400 font-semibold border border-blue-200 dark:border-blue-500/20' 
                    : 'hover:bg-slate-100 dark:hover:bg-white/5 text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-100 font-medium'
                }`}
              >
                <div className="relative z-10 flex items-center gap-3">
                    {item.icon}
                    <span className="truncate">{item.name}</span>
                </div>
                {isActive && (
                    <div className="absolute right-3 top-1/2 -translate-y-1/2 opacity-50">
                        <ChevronRight size={14} />
                    </div>
                )}
              </NavLink>
            );
          })}
        </div>

        <div className="p-4 border-t border-slate-200 dark:border-white/10 flex gap-2">
            <button 
                onClick={handleLogout}
                className="flex-1 flex items-center gap-3 px-4 py-2 text-sm font-medium text-slate-600 dark:text-slate-400 hover:text-red-500 dark:hover:text-red-400 transition-colors"
            >
                <LogOut size={16} />
                Sign Out
            </button>
            <button
                onClick={() => {
                    setShowAdminModal(true);
                    setIsAdminAuthenticated(false);
                    setAdminPassword('');
                }}
                className="p-2 rounded-lg text-slate-400 hover:bg-slate-100 dark:hover:bg-white/10 hover:text-blue-500 transition-colors"
                title="System Configuration"
            >
                <Lock size={16} />
            </button>
        </div>
      </aside>

      {/* Main Content Area */}
      <main className="flex-1 h-screen overflow-y-auto overflow-x-hidden relative flex flex-col">
        {/* Header */}
        <header className="h-16 glass-panel border-b-0 sticky top-0 z-40 flex items-center justify-between px-4 md:px-8 backdrop-blur-xl shadow-sm">
          <div className="md:hidden flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-blue-500 to-purple-500 flex items-center justify-center font-bold text-white">
              T
            </div>
            <span className="font-bold text-slate-900 dark:text-white">TTSP</span>
          </div>
          
          <div className="hidden md:flex font-semibold text-lg opacity-90 text-slate-800 dark:text-slate-100">
            {NAV_ITEMS.find(n => n.path === location.pathname)?.name || 'Management Review'}
          </div>

          <div className="flex items-center gap-3 md:gap-4">
            <button 
                onClick={() => setShowAppearance(true)}
                className="p-2 rounded-full hover:bg-slate-100 dark:hover:bg-white/10 transition-colors relative group text-slate-600 dark:text-slate-300"
                title="Appearance Settings"
            >
                <Palette size={20} />
            </button>
            <button className="p-2 rounded-full hover:bg-slate-100 dark:hover:bg-white/10 transition-colors relative text-slate-600 dark:text-slate-300">
              <Bell size={20} />
              <span className="absolute top-1.5 right-2 w-2 h-2 bg-red-500 rounded-full animate-pulse" />
            </button>
            
            <div className="flex items-center gap-3 pl-3 border-l border-slate-200 dark:border-white/10">
                <div className="text-right hidden sm:block">
                    <div className="text-xs font-bold text-slate-900 dark:text-white">
                        {user?.user_metadata?.full_name || 'Guest User'}
                    </div>
                    <div className="text-[10px] text-slate-500 dark:text-slate-400 truncate max-w-[120px]">
                        {user?.email || ''}
                    </div>
                </div>
                <div className="w-9 h-9 rounded-full bg-gradient-to-br from-blue-500 to-purple-600 border-2 border-white dark:border-white/20 flex items-center justify-center text-sm font-bold text-white shadow-md">
                   {getInitials()}
                </div>
            </div>
          </div>
        </header>

        <div className="p-4 md:p-8 max-w-7xl mx-auto w-full pb-28 md:pb-8">
          {children}
        </div>
      </main>

      {/* Futuristic Appearance Settings Modal */}
      {showAppearance && (
        <>
            <div className="fixed inset-0 z-50 bg-black/20 dark:bg-black/50 backdrop-blur-sm" onClick={() => setShowAppearance(false)} />
            <div className="fixed top-20 right-4 md:right-8 z-50 w-80 glass-panel border border-slate-200 dark:border-white/20 rounded-2xl p-6 shadow-2xl animate-slide-in-right bg-white/90 dark:bg-slate-900/90">
                <div className="flex justify-between items-center mb-6">
                    <h3 className="font-bold text-lg flex items-center gap-2 text-slate-900 dark:text-white">
                        <Monitor size={18} /> UI Customization
                    </h3>
                    <button onClick={() => setShowAppearance(false)} className="hover:bg-slate-100 dark:hover:bg-white/10 rounded-full p-1 text-slate-500 dark:text-slate-400">
                        <X size={18} />
                    </button>
                </div>

                <div className="space-y-6">
                    <div>
                        <label className="text-xs uppercase font-bold opacity-60 mb-3 block text-slate-500 dark:text-slate-400">Color Mode</label>
                        <div className="bg-slate-100 dark:bg-white/5 p-1 rounded-xl flex border border-slate-200 dark:border-white/10">
                            <button 
                                onClick={() => setIsDarkMode(false)}
                                className={`flex-1 py-2 rounded-lg flex items-center justify-center gap-2 text-sm font-medium transition-all ${!isDarkMode ? 'bg-white text-blue-600 shadow-md' : 'text-slate-500 hover:bg-black/5'}`}
                            >
                                <Sun size={16} /> Light
                            </button>
                            <button 
                                onClick={() => setIsDarkMode(true)}
                                className={`flex-1 py-2 rounded-lg flex items-center justify-center gap-2 text-sm font-medium transition-all ${isDarkMode ? 'bg-slate-700 text-white shadow-md' : 'text-slate-400 hover:bg-white/5'}`}
                            >
                                <Moon size={16} /> Dark
                            </button>
                        </div>
                    </div>

                    <div>
                        <label className="text-xs uppercase font-bold opacity-60 mb-3 block text-slate-500 dark:text-slate-400">Atmosphere Theme</label>
                        <div className="grid grid-cols-2 gap-3">
                            {THEMES.map((t) => (
                                <button
                                    key={t.value}
                                    onClick={() => setTheme(t.value)}
                                    className={`relative h-16 rounded-xl border-2 transition-all overflow-hidden group ${
                                        currentTheme === t.value ? 'border-blue-500 scale-105 shadow-md ring-2 ring-blue-500/20' : 'border-transparent hover:scale-105 hover:border-slate-300 dark:hover:border-white/10'
                                    }`}
                                >
                                    <div className={`absolute inset-0 ${t.class} opacity-80`} />
                                    <div className={`absolute inset-0 flex items-center justify-center font-bold text-xs z-10 text-white text-shadow shadow-black/50`}>
                                        {t.name}
                                    </div>
                                </button>
                            ))}
                        </div>
                    </div>
                </div>
            </div>
        </>
      )}

      {/* Admin / Config Modal */}
      {showAdminModal && (
        <div className="fixed inset-0 z-[60] flex items-center justify-center p-4 bg-black/60 backdrop-blur-md animate-fade-in">
            <div className="glass-panel w-full max-w-2xl rounded-2xl shadow-2xl overflow-hidden flex flex-col border border-slate-200 dark:border-white/10">
                <div className="p-4 border-b border-slate-200 dark:border-white/10 flex justify-between items-center bg-slate-50 dark:bg-white/5">
                    <h3 className="font-bold text-lg flex items-center gap-2 text-slate-900 dark:text-white">
                        <Lock size={18} className="text-blue-500" /> System Configuration
                    </h3>
                    <button onClick={() => setShowAdminModal(false)} className="hover:bg-slate-200 dark:hover:bg-white/10 rounded-full p-1 text-slate-500 dark:text-white">
                        <X size={20} />
                    </button>
                </div>

                <div className="p-8">
                    {!isAdminAuthenticated ? (
                        <div className="flex flex-col items-center justify-center space-y-4">
                            <div className="w-16 h-16 bg-slate-100 dark:bg-white/5 rounded-full flex items-center justify-center mb-2">
                                <Lock size={32} className="text-slate-400" />
                            </div>
                            <h4 className="text-xl font-bold text-slate-800 dark:text-white">Protected Area</h4>
                            <p className="text-sm text-slate-500 dark:text-slate-400 text-center max-w-xs">
                                Enter the administrator access code to view Supabase configuration details.
                            </p>
                            <input 
                                type="password" 
                                className="w-64 text-center text-2xl tracking-widest font-mono p-3 rounded-xl border border-slate-300 dark:border-white/20 bg-white dark:bg-black/30 text-slate-900 dark:text-white focus:ring-2 focus:ring-blue-500 outline-none"
                                placeholder="•••••••"
                                value={adminPassword}
                                onChange={(e) => setAdminPassword(e.target.value)}
                                onKeyDown={(e) => e.key === 'Enter' && handleAdminAuth()}
                                autoFocus
                            />
                            <button 
                                onClick={handleAdminAuth}
                                className="w-64 py-3 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-xl shadow-lg shadow-blue-500/30 transition-all active:scale-95"
                            >
                                Unlock
                            </button>
                        </div>
                    ) : (
                        <div className="space-y-6 overflow-y-auto max-h-[60vh] pr-2 custom-scrollbar">
                            <div className="bg-green-50 dark:bg-green-500/10 border border-green-200 dark:border-green-500/20 p-4 rounded-xl flex items-center gap-3">
                                <Check size={20} className="text-green-600 dark:text-green-400" />
                                <span className="text-green-800 dark:text-green-200 font-medium">Access Granted: Developer Mode</span>
                            </div>

                            <div className="space-y-2">
                                <h5 className="font-bold text-slate-800 dark:text-white">1. Environment Variables (.env)</h5>
                                <p className="text-xs text-slate-500 dark:text-slate-400">Create a <code>.env</code> file in your project root.</p>
                                <div className="relative group">
                                    <pre className="bg-slate-900 text-slate-300 p-4 rounded-xl text-xs font-mono overflow-x-auto border border-slate-800">
{`VITE_SUPABASE_URL=your_project_url
VITE_SUPABASE_ANON_KEY=your_anon_key`}
                                    </pre>
                                </div>
                            </div>

                            <div className="space-y-2">
                                <h5 className="font-bold text-slate-800 dark:text-white">2. SQL Migration Script (PDR + Users)</h5>
                                <p className="text-xs text-slate-500 dark:text-slate-400">Copy this to the Supabase SQL Editor. It creates tables and sets up triggers for Auto-User creation.</p>
                                <div className="relative group">
                                    <button 
                                        onClick={() => copyToClipboard(SQL_SCHEMA)}
                                        className="absolute top-2 right-2 p-2 bg-slate-800 hover:bg-slate-700 text-white rounded-lg opacity-0 group-hover:opacity-100 transition-opacity"
                                        title="Copy SQL"
                                    >
                                        {copied ? <Check size={14} /> : <Copy size={14} />}
                                    </button>
                                    <pre className="bg-slate-900 text-blue-300 p-4 rounded-xl text-xs font-mono overflow-x-auto border border-slate-800 h-64">
                                        {SQL_SCHEMA}
                                    </pre>
                                </div>
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>
      )}

      {/* Enhanced Mobile Bottom Navigation (Scrollable) */}
      <nav className="md:hidden fixed bottom-0 left-0 right-0 h-20 glass-panel border-t-0 z-50 flex items-center backdrop-blur-xl px-4 overflow-x-auto gap-6 hide-scrollbar shadow-[0_-5px_15px_rgba(0,0,0,0.1)]">
         {NAV_ITEMS.map((item) => {
           const isActive = location.pathname === item.path;
           return (
             <NavLink
                key={item.name}
                to={item.path}
                className={`flex flex-col items-center justify-center min-w-[64px] h-full gap-1.5 transition-all ${
                  isActive ? 'text-blue-600 dark:text-blue-400 scale-105' : 'text-slate-400 dark:text-slate-500 opacity-80'
                }`}
             >
                <div className={`p-2 rounded-2xl ${isActive ? 'bg-blue-100 dark:bg-blue-500/20' : 'bg-transparent'}`}>
                    {React.cloneElement(item.icon as React.ReactElement<any>, { size: 22 })}
                </div>
                <span className={`text-[10px] font-bold truncate w-full text-center max-w-[70px] ${isActive ? 'opacity-100' : 'opacity-60'}`}>
                    {item.name}
                </span>
             </NavLink>
           );
         })}
         {/* Logout for mobile */}
          <button
            onClick={handleLogout}
            className="flex flex-col items-center justify-center min-w-[64px] h-full gap-1.5 text-red-500/70 hover:text-red-500"
          >
            <div className="p-2 rounded-2xl bg-red-500/10">
                <LogOut size={22} />
            </div>
            <span className="text-[10px] font-bold opacity-60">Logout</span>
          </button>
      </nav>

      <style>{`
        .hide-scrollbar::-webkit-scrollbar {
            display: none;
        }
        .hide-scrollbar {
            -ms-overflow-style: none;
            scrollbar-width: none;
        }
      `}</style>
    </div>
  );
};

export default Layout;